title: Horace Jones. Architect of Tower Bridge.
email: harry@harrylascelles.com
description: >- # this means to ignore newlines until "baseurl:"
  Horace Jones. Architect of Tower Bridge.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.horacejones.org" # the base hostname & protocol for your site, e.g. http://example.com
markdown: kramdown

#google_analytics: UA-141179634-1

plugins:
- jekyll-sitemap
- jekyll-seo-tag
